import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import Relogio from "@/components/MagiaDoJSX/Relogio"; 

const data = new Date();

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "React Lab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* ALTERAÇÃO: bg-black e text-white */}
      <body className='flex flex-col justify-start gap-4 p-20 items-center min-h-screen bg-black text-white'>
        
        <header className="flex flex-col items-center">
          <h1 className="text-3xl font-bold mb-4">React & Next.js</h1>
          <nav className="flex gap-4 text-blue-400 hover:text-blue-300 underline-offset-4">
            <Link href="/" className="hover:underline">Intro</Link>
            <Link href="/sobre" className="hover:underline">Sobre</Link>
            <Link href="/tecnologias" className="hover:underline">Tecnologias</Link>
            <Link href="/contador" className="hover:underline font-bold">Contador</Link>
            <Link href="/input" className="hover:underline font-bold">Input & Tasks</Link>
            <Link href="/produtos" className="hover:text-cyan-400 hover:scale-105 transition-all duration-300 text-white font-bold border-b-2 border-cyan-500 pb-1">
        DEISIshop
    </Link>
    <Link href="/carrinho" className="hover:text-green-400 hover:scale-105 transition-all duration-300 font-bold border-b-2 border-transparent hover:border-green-500 pb-1">
    Carrinho
</Link>
          </nav>
        </header>


        <main className="bg-zinc-900 p-5 rounded-2xl max-w-2xl min-h-[70vh] shadow-lg w-full border border-zinc-800">
          {children}
        </main>
        
        <footer className="text-gray-500 text-sm flex flex-col items-center gap-2 mt-4">
          <span>DIW {data.getFullYear()}</span>
          <Relogio />
        </footer>

      </body>
    </html>
  );
}